import { z } from 'zod';

export const createLedgerSchema = z.object({
  partyName: z.string().min(2, 'Party name required'),
  realName: z.string().optional(),
  userName: z.string().optional(),
  groupName: z.string().optional(),
  agentId: z.number().int().optional(),
  agentName: z.string().optional(),
  distributorId: z.number().int().optional(),
  telegram: z.string().optional(),
  mobile: z.string().optional(),
  address: z.string().optional(),
  grantor: z.string().optional(),
  refLedger: z.string().optional(),
  daraRate: z.number().positive().default(90),
  akharRate: z.number().positive().default(9),
  commissionRate: z.number().min(0).max(100).default(0),
  hissaPercentage: z.number().min(0).max(100).default(0),
  betLimit: z.number().min(0).default(0),
  capping: z.number().min(0).default(0),
  hasLimit: z.boolean().default(false),
  vapsiTpr: z.string().optional(),
  rebate: z.number().optional(),
  tpComm: z.string().optional(),
  tpRebate: z.string().optional(),
  hissa: z.string().optional(),
  limitType: z.string().optional(),
  isLocked: z.boolean().default(false),
  isRisky: z.boolean().default(false),
}).passthrough();
